### ISSUE TITLE
CPU Temperature alert giving 'No data' on Raspberry Pi CM3+

### ISSUE THREAD

**Issue by geerlingguy** [carlosedp/cluster-monitoring#39]
I'm testing this out on a Turing Pi cluster, with 7 Pi Compute Module 3+ boards.

On my Grafana dashboard, I'm seeing no data for CPU temperature:

<img width="340" alt="Screen Shot 2020-05-23 at 6 33 25 PM" src="https://user-images.githubusercontent.com/481677/82742454-ff3faa00-9d23-11ea-95e7-6b3c3e72f6fb.png">

I'm going to dig in and see where the monitor is supposed to be running. I modified the `vars.jsonnet` file like so, for my cluster:

```
{
  _config+:: {
    namespace: 'monitoring',
  },
  // Enable or disable additional modules
  modules: [
    {
      // After deployment, run the create_gmail_auth.sh script from scripts dir.
      name: 'smtpRelay',
      enabled: false,
      file: import 'smtp_relay.jsonnet',
    },
    {
      name: 'armExporter',
      enabled: true,
      file: import 'arm_exporter.jsonnet',
    },
    {
      name: 'upsExporter',
      enabled: false,
      file: import 'ups_exporter.jsonnet',
    },
    {
      name: 'metallbExporter',
      enabled: false,
      file: import 'metallb.jsonnet',
    },
    {
      name: 'traefikExporter',
      enabled: false,
      file: import 'traefik.jsonnet',
    },
    {
      name: 'elasticExporter',
      enabled: false,
      file: import 'elasticsearch_exporter.jsonnet',
    },
  ],

  k3s: {
    enabled: true,
    master_ip: ['10.0.100.163'],
  },

  // Domain suffix for the ingresses
  suffixDomain: '10.0.100.74.nip.io',
  // If TLSingress is true, a self-signed HTTPS ingress with redirect will be created
  TLSingress: true,
  // If UseProvidedCerts is true, provided files will be used on created HTTPS ingresses.
  // Use a wildcard certificate for the domain like ex. "*.192.168.99.100.nip.io"
  UseProvidedCerts: false,
  TLSCertificate: importstr 'server.crt',
  TLSKey: importstr 'server.key',

  // Setting these to false, defaults to emptyDirs
  enablePersistence: {
    prometheus: false,
    grafana: false,
  },

  // Grafana "from" email
  grafana: {
    from_address: 'myemail@example.com',
  },
}
```

**Comment by geerlingguy** [comment]
Checking on the DaemonSet:

```
# kubectl get ds -n monitoring
NAME            DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                   AGE
node-exporter   7         7         7       7            7           kubernetes.io/os=linux          140m
arm-exporter    0         0         0       0            0           beta.kubernetes.io/arch=arm64   11m
```

**Comment by geerlingguy** [comment]
Also after editing the `vars.jsonnet` file and re-`make`ing everything I'm getting unrelated error:

```
failed: [10.0.100.163] (item=/home/pirate/cluster-monitoring/manifests/node-exporter-daemonset.yaml) => {"ansible_loop_var": "item", "changed": false, "error": 422, "item": "/home/pirate/cluster-monitoring/manifests/node-exporter-daemonset.yaml", "msg": "Failed to patch object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"DaemonSet.apps \\\\\"node-exporter\\\\\" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{\\\\\"app\\\\\":\\\\\"node-exporter\\\\\", \\\\\"app.kubernetes.io/name\\\\\":\\\\\"node-exporter\\\\\"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable\",\"reason\":\"Invalid\",\"details\":{\"name\":\"node-exporter\",\"group\":\"apps\",\"kind\":\"DaemonSet\",\"causes\":[{\"reason\":\"FieldValueInvalid\",\"message\":\"Invalid value: v1.LabelSelector{MatchLabels:map[string]string{\\\\\"app\\\\\":\\\\\"node-exporter\\\\\", \\\\\"app.kubernetes.io/name\\\\\":\\\\\"node-exporter\\\\\"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable\",\"field\":\"spec.selector\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422}
```

(That's from Ansible—basically it's trying to change the selector but that field is immutable. Seems unrelated to the `armexporter` though... I'm not sure why the DS has `0` desired instances.

**Comment by geerlingguy** [comment]
I wonder if this issue might be related to something like https://github.com/kubernetes/kubernetes/issues/51785. I'm going to manually delete the daemonset and re-create it and see if that works.

**Comment by geerlingguy** [comment]
Ah... I think this is the issue:

```yaml
      nodeSelector:                                                                                                                                                                                                      
        beta.kubernetes.io/arch: arm64
```

**Comment by geerlingguy** [comment]
And I'm getting CPU temperature values, yay!

<img width="758" alt="Screen Shot 2020-05-23 at 7 16 57 PM" src="https://user-images.githubusercontent.com/481677/82742957-036ec600-9d2a-11ea-9cea-f21e2be0bd13.png">

Is there a way you can set it to a set of `arm64|arm`?

**Comment by geerlingguy** [comment]
Although now I'm not getting the other values (CPU, Memory, etc.)—only the temperature data and up/down status :/ — possibly something silly I did though. I might just wipe the cluster and reinstall again, now that there are a number of small tweaks.

**Comment by geerlingguy** [comment]
I replaced the `nodeSelector` with `affinity`, and it's now scheduling things correctly:

```yaml
    spec:                                                                                 
      affinity:                                                                           
        nodeAffinity:                                                  
          requiredDuringSchedulingIgnoredDuringExecution:              
            nodeSelectorTerms:                                         
            - matchExpressions:                                        
              - key: kubernetes.io/arch                                
                operator: In                                           
                values:                                                
                - arm                                                  
                - arm64 
```

I may submit a PR in a few minutes; I'm also testing the fix for #40 first.
